[package]
name = "diesel-enums"
version = "0.1.0"
edition.workspace = true

[dependencies]
diesel-enums-core = { path = "../core" }
diesel-enum-checked = { path = "../proc-macro/" }

[features]
default = ["pretty-test-errors"]

pretty-test-errors = ["diesel-enums-core/pretty-test-errors"]
